title: “Bryan Barnes”  
email: “jbryanbarnes@gmail.com”  
linkedin: “https://linkedin.com/in/jbryanbarnes”  

collections:  
  projects:  
    output: true  
    permalink: /projects/:name/  

defaults:  
  - scope:  
      path: “”  
      type: projects  
    values:  
      layout: project  